### PR TITLE
Add new features

### PR DESCRIPTION
**Pull request by n-serrette**
# New Features

## Ellipse and Ellipse graph
Close to ring, the main difference is the height and width required properties.

## Text
A simple implementation of static and variable text.

## Graduations
Add graduations on the elements
Three new properties on all elements:
* graduated
* number_graduation
* space_between_graduation / angle_between_graduation

### PS
This is my first time working with Lua and cairo, so the code might be dirty

### CODE REVIEW

**Comment by fisadev** [comment]
Thanks for the work on this! Very welcome additions :)

I'll give them a try tomorrow, and then will merge it.

**Comment by fisadev** [comment]
Hey, I've been testing it, and I found an issue, would you mind taking a look at it so I can merge it with the fix?

The issue is that in a ring_graph example, the bar disappears when I add graduations to the graph. This is the example:

    {
        kind = 'ring_graph',
        conky_value = 'fs_used_perc /home/',
        center = {x = 90, y = 375},
        radius = 35,
        background_color = graphs_color,
        background_alpha = 0.3,
        background_thickness = 2, 
        bar_color = graphs_color,
        bar_alpha = 1,
        bar_thickness = 5,
        start_angle = 45,
        end_angle = -225,
        graduated= true,
        number_graduation= 20,
        space_between_graduation=4,
    },

Without graduations, it shows a bar with about 60% value. With graduations, it only shows the graduated background, but no bar on top of it showing the value of the graph.

**Comment by n-serrette** [comment]
I will look at it as soon as I can, Thanks

**Comment by n-serrette** [comment]
I have fixed the issue. 
You have made a little mistake on your ring_graph, you have used space_between_graduation instead of angle_between graduation. 
Maybe I should simplify this by using the same property, what do you think?

**Comment by fisadev** [comment]
Merged, thanks for the work on this, and sorry for the delay! :)

**Pull request merged**
